"""StudyPlan model - a personalized daily study plan generated for a user."""

from datetime import datetime
from typing import TYPE_CHECKING, Optional

from sqlalchemy import Boolean, DateTime, ForeignKey, Integer, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from src.models.base import Base

if TYPE_CHECKING:
    from src.models.user import User


class StudyPlan(Base):
    """A personalized, date-bound study plan generated by the planner agent.

    ``daily_plan_json`` is a JSON array where each element represents one
    day and contains the topics to study, estimated time, and linked
    resources. The plan is regenerated whenever the user updates their
    exam date or completed topics.
    """

    __tablename__ = "study_plans"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)

    title: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)

    # Plan content - JSON array of daily entries
    daily_plan_json: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Target exam context
    target_exam_name: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    exam_date: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    total_days: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)

    # User inputs used to generate the plan
    available_hours_per_day: Mapped[Optional[float]] = mapped_column(nullable=True)
    weak_topics_json: Mapped[Optional[str]] = mapped_column(
        Text, nullable=True
    )  # JSON list of topic IDs

    # Status
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)

    # Foreign key
    user_id: Mapped[int] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    # Relationships
    user: Mapped["User"] = relationship("User", back_populates="study_plans")

    def __repr__(self) -> str:
        return (
            f"<StudyPlan id={self.id} user_id={self.user_id} "
            f"target={self.target_exam_name!r} days={self.total_days}>"
        )
